// Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// icon-color: purple; icon-glyph: magic;
{
    "theme": {
        "clientLogoURL": "/static/clients/themes/Guess Logo.png?cache=b757d9fc3e6eae1e87c4b13e1075c5d9d1b2a0a1baadce7b36737e22ab0efd05",
        "backgroundColor": "#d2d2d2",
        "backgroundImageURL": null
    },
    "redirectURL": null,
    "delegations": {
        "delegationList": []
    },
    "versionAlias": "PROD2_CURR",
    "clientType": "1",
    "insightsUri": null,
    "reportsUri": null,
    "marketplaceUri": null,
    "userMenu": {
        "navigation": {
            "globalOpts": [],
            "iconBar": [],
            "footer": [
                {
                    "rid": null,
                    "roid": "",
                    "label": "Privacy",
                    "navItemType": "revit.navigation.NavItem",
                    "href": "http://privacy.adp.com/privacy.html?locale=$locale"
                },
                {
                    "rid": null,
                    "roid": "",
                    "label": "Legal",
                    "navItemType": "revit.navigation.NavItem",
                    "href": "/portal/public/termscondition.jsp"
                },
                {
                    "rid": null,
                    "roid": "",
                    "label": "Requirements",
                    "navItemType": "revit.navigation.NavItem",
                    "href": "https://support.adp.com/pub/paas/login_page/common/$locale/empl/netscr/base/logon/wfn_req.htm"
                },
                {
                    "rid": null,
                    "roid": "10013",
                    "label": "Product Feedback",
                    "navItemType": "revit.navigation.NavItem",
                    "href": "/myportal/feedback/feedback/productFeedback.faces"
                }
            ],
            "mainNav": [
                {
                    "rid": "Myself",
                    "roid": "2000",
                    "label": "Myself",
                    "navItemType": "revit/navigation/NavItem",
                    "submenus": [
                        {
                            "title": "Pay",
                            "column": 1,
                            "items": [
                                {
                                    "rid": "PayandAnnualStatements",
                                    "roid": "77019870",
                                    "label": "Pay & Tax Statements",
                                    "href": "https://my.adp.com/static/redbox/#/pay?utm_source=WFN",
                                    "sessionKeepAlive": false,
                                    "pingUri": null,
                                    "navItemType": "revit/navigation/NavItem",
                                    "hasFullScreen": true,
                                    "simplePortlet": true,
                                    "useIframe": false,
                                    "publish": false,
                                    "showHelp": false,
                                    "frameHeight": 0,
                                    "appView": "PayandAnnualStatements",
                                    "openPopup": false,
                                    "hasInsights": false,
                                    "videoActions": null,
                                    "country": null,
                                    "liveChat": null,
                                    "internationalSearchMeta": "Pay & Tax Statements",
                                    "showFieldGrabber": false
                                }
                            ]
                        }
                    ]
                }
            ],
            "dock": [],
            "preferences": []
        },
        "configuration": {
            "mastheadOptions": {
                "firstName": "Andres",
                "lastName": "Magana"
            }
        },
        "wfnVersion": "23.38",
        "bootstrapUrl": "/wfn-static/v23/bootstrap.js",
        "crossborderClient": false,
        "userFavorites": {
            "favorites": {},
            "hasExpandedMenu": true
        },
        "eapFeatures": [
            "BENEFITS_DASHBOARD_REDESIGN",
            "CalculatePreviewPayrollMicroservice",
            "CreateLoadFilesThroughTurbo",
            "ENABLE_AAEP_CA",
            "ENABLE_DE_AND_I_PREFERRED_NAME",
            "ENABLE_ESS_BENEFITS_ONEUX",
            "ENABLE_OB_DATA_ON_REDIS_ONPREM",
            "ENABLE_OB_ENHANCED_ESIGN",
            "ENABLE_OFFCYCLE_PAY",
            "ENABLE_PAYROLL_DASHBOARD_MULTI_COMPANY_SUPPORT",
            "ENABLE_PTO_MANAGER_MASS_APPROVAL_ENHANCEMENT",
            "ENABLE_PTO_PRACTITIONER_MASS_APPROVAL_ENHANCEMENT",
            "ENABLE_SKIP_FOR_WACARES_RULE",
            "ENABLE_WFNHR_MSS_NEWHIRE",
            "ENABLE_WFNHR_MYTEAM_DASHBOARD",
            "ENABLE_WFNHR_UNIFIED_EMPLOYEE_PROFILE",
            "ENABLE_WORKFLOW_PREVIEW_PAGE",
            "EnableACSWorkerSFV",
            "EnableACSWorkerSIA",
            "EnableACSWorkerSOR",
            "EnableACSWorkerSPRAssociateCreation",
            "EnableACSWorkerSPRClientAgentCreation",
            "EnableACSWorkerSPRUserChange",
            "EnableACSWorkerSPRUserCreation",
            "EnableACSWorkerSPRUserDeletion",
            "EnableBenefitsPracEnrollmentTechRefresh",
            "EnableContextualHomeNotification",
            "EnableContextualHomePage",
            "EnableEnterpriseSearchTechRefresh",
            "EnableMissingTaxIdNotifications",
            "EnableNewShell",
            "EnablePaperless",
            "EnablePayLens",
            "EnablePlanAdminUITechRefresh",
            "EnablePreferencesTechRefresh",
            "EnableSCPRegistrationService",
            "EnableWfnShell",
            "EnterpriseSearch",
            "RTPReportsSQLQueriesOptimized",
            "SimplifiedUA",
            "SimplifiedUAForMyADP",
            "chp-backup-banner-02042022",
            "chp-enhanced-ttd",
            "chp-masonry",
            "chp-preview"
        ],
        "processingRegion": "0037"
    },
    "timeout": 1200000,
    "exclusiveDataLock": false,
    "audioEyeEnabled": false,
    "countryCodes": [
        "CA",
        "US"
    ],
    "wfnSecToken": "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjoiQVJkMU14bGFQd0FvUjZnbzZmUS8yR2hjZXNXM0VqUHFMalY3QURJOC9jTmFUTkVwSTI0bzI2Y0tJaEd6ZWtVcG1mYkp6b1Qvay9JOWV5MFlQSTYvVHlycGhZcXVPL2JPakttOUkyMDNxSUdDMEp0ckR2VWhyODJNK01JdXRFYUhFOWU2RmQrL3d4anRlT2lvSXZ1L25TVXY0ZXJLbTltSWgza1ZYY2xHdWlEK0cvN3dXcXhGY2xnUHBJYTJ5Zi9sVVd0VWJMemlhTU92ZExBMUt5YWprbXNHeVN3UUREb3N1ZEcvWldMKy9Fajc3ZnQ4eVZqbk16RTlVdFViRzlZNSIsImlhdCI6MTY5NTQzNDA3NywidHhuIjoiMDUwYzQzMzQtMzhjZi00Yjg5LWJmMTctNDY2OGJiYjEzMDIxIn0.jJR52i0etf95KjKhqKs7aCQDa2Ag9AAgbmFhhLDED4c",
    "PAASVERSION": "portal-static",
    "ADPLangLocale": "en_US",
    "globalContextObject": {
        "countriesCodeObj": {
            "countriesJson": {
                "PR": "PRI",
                "PS": "PSE",
                "PT": "PRT",
                "PW": "PLW",
                "PY": "PRY",
                "QA": "QAT",
                "AD": "AND",
                "AE": "ARE",
                "AF": "AFG",
                "AG": "ATG",
                "AI": "AIA",
                "AL": "ALB",
                "AM": "ARM",
                "AO": "AGO",
                "AQ": "ATA",
                "AR": "ARG",
                "AS": "ASM",
                "AT": "AUT",
                "RE": "REU",
                "AU": "AUS",
                "AW": "ABW",
                "AX": "ALA",
                "AZ": "AZE",
                "RO": "ROU",
                "BA": "BIH",
                "BB": "BRB",
                "RS": "SRB",
                "BD": "BGD",
                "BE": "BEL",
                "RU": "RUS",
                "BF": "BFA",
                "BG": "BGR",
                "RW": "RWA",
                "BH": "BHR",
                "BI": "BDI",
                "BJ": "BEN",
                "BL": "BLM",
                "BM": "BMU",
                "BN": "BRN",
                "BO": "BOL",
                "SA": "SAU",
                "BQ": "BES",
                "SB": "SLB",
                "BR": "BRA",
                "SC": "SYC",
                "BS": "BHS",
                "SD": "SDN",
                "BT": "BTN",
                "SE": "SWE",
                "BV": "BVT",
                "SG": "SGP",
                "BW": "BWA",
                "SH": "SHN",
                "SI": "SVN",
                "BY": "BLR",
                "SJ": "SJM",
                "BZ": "BLZ",
                "SK": "SVK",
                "SL": "SLE",
                "SM": "SMR",
                "SN": "SEN",
                "SO": "SOM",
                "CA": "CAN",
                "SR": "SUR",
                "CC": "CCK",
                "SS": "SSD",
                "CD": "COD",
                "ST": "STP",
                "CF": "CAF",
                "SV": "SLV",
                "CG": "COG",
                "CH": "CHE",
                "SX": "SXM",
                "CI": "CIV",
                "SY": "SYR",
                "SZ": "SWZ",
                "CK": "COK",
                "CL": "CHL",
                "CM": "CMR",
                "CN": "CHN",
                "CO": "COL",
                "CR": "CRI",
                "TC": "TCA",
                "TD": "TCD",
                "CU": "CUB",
                "TF": "ATF",
                "CV": "CPV",
                "TG": "TGO",
                "CW": "CUW",
                "TH": "THA",
                "CX": "CXR",
                "CY": "CYP",
                "TJ": "TJK",
                "CZ": "CZE",
                "TK": "TKL",
                "TL": "TLS",
                "TM": "TKM",
                "TN": "TUN",
                "TO": "TON",
                "TR": "TUR",
                "TT": "TTO",
                "DE": "DEU",
                "TV": "TUV",
                "TW": "TWN",
                "DJ": "DJI",
                "TZ": "TZA",
                "DK": "DNK",
                "DM": "DMA",
                "DO": "DOM",
                "UA": "UKR",
                "UG": "UGA",
                "DZ": "DZA",
                "UM": "UMI",
                "EC": "ECU",
                "US": "USA",
                "EE": "EST",
                "EG": "EGY",
                "EH": "ESH",
                "UY": "URY",
                "UZ": "UZB",
                "VA": "VAT",
                "ER": "ERI",
                "VC": "VCT",
                "ES": "ESP",
                "ET": "ETH",
                "VE": "VEN",
                "VG": "VGB",
                "VI": "VIR",
                "VN": "VNM",
                "VU": "VUT",
                "FI": "FIN",
                "FJ": "FJI",
                "FK": "FLK",
                "FM": "FSM",
                "FO": "FRO",
                "FR": "FRA",
                "WF": "WLF",
                "GA": "GAB",
                "GB": "GBR",
                "WS": "WSM",
                "GD": "GRD",
                "GE": "GEO",
                "GF": "GUF",
                "GG": "GGY",
                "GH": "GHA",
                "GI": "GIB",
                "GL": "GRL",
                "GM": "GMB",
                "GN": "GIN",
                "GP": "GLP",
                "GQ": "GNQ",
                "GR": "GRC",
                "GS": "SGS",
                "GT": "GTM",
                "GU": "GUM",
                "GW": "GNB",
                "GY": "GUY",
                "HK": "HKG",
                "HM": "HMD",
                "HN": "HND",
                "HR": "HRV",
                "HT": "HTI",
                "YE": "YEM",
                "HU": "HUN",
                "ID": "IDN",
                "YT": "MYT",
                "IE": "IRL",
                "IL": "ISR",
                "IM": "IMN",
                "IN": "IND",
                "IO": "IOT",
                "ZA": "ZAF",
                "IQ": "IRQ",
                "IR": "IRN",
                "IS": "ISL",
                "IT": "ITA",
                "ZM": "ZMB",
                "JE": "JEY",
                "ZW": "ZWE",
                "JM": "JAM",
                "JO": "JOR",
                "JP": "JPN",
                "KE": "KEN",
                "KG": "KGZ",
                "KH": "KHM",
                "KI": "KIR",
                "KM": "COM",
                "KN": "KNA",
                "KP": "PRK",
                "KR": "KOR",
                "KW": "KWT",
                "KY": "CYM",
                "KZ": "KAZ",
                "LA": "LAO",
                "LB": "LBN",
                "LC": "LCA",
                "LI": "LIE",
                "LK": "LKA",
                "LR": "LBR",
                "LS": "LSO",
                "LT": "LTU",
                "LU": "LUX",
                "LV": "LVA",
                "LY": "LBY",
                "MA": "MAR",
                "MC": "MCO",
                "MD": "MDA",
                "ME": "MNE",
                "MF": "MAF",
                "MG": "MDG",
                "MH": "MHL",
                "MK": "MKD",
                "ML": "MLI",
                "MM": "MMR",
                "MN": "MNG",
                "MO": "MAC",
                "MP": "MNP",
                "MQ": "MTQ",
                "MR": "MRT",
                "MS": "MSR",
                "MT": "MLT",
                "MU": "MUS",
                "MV": "MDV",
                "MW": "MWI",
                "MX": "MEX",
                "MY": "MYS",
                "MZ": "MOZ",
                "NA": "NAM",
                "NC": "NCL",
                "NE": "NER",
                "NF": "NFK",
                "NG": "NGA",
                "NI": "NIC",
                "NL": "NLD",
                "NO": "NOR",
                "NP": "NPL",
                "NR": "NRU",
                "NU": "NIU",
                "NZ": "NZL",
                "OM": "OMN",
                "PA": "PAN",
                "PE": "PER",
                "PF": "PYF",
                "PG": "PNG",
                "PH": "PHL",
                "PK": "PAK",
                "PL": "POL",
                "PM": "SPM",
                "PN": "PCN"
            }
        },
        "_sessionContext": {
            "client": {
                "isADP": "false",
                "appId": "WFNPortal",
                "clientType": 2,
                "clientId": "guessw",
                "orgOID": "G3DRDEV9MMNJ9FXW",
                "products": "150,166,231,2378,130,181,182,183,104,108,212,111,2138,2141,2140,102,127,131,121,122,134,152,153,175,178,164,135,2132,160,209,2246,2185,140,1002,2266",
                "partnerIndicator": "CLIENT",
                "classificationCode": "CL",
                "farmId": "PORTALWFN60",
                "clientName": "Guess, Inc.",
                "companyCode": "RTW"
            },
            "uaMode": {
                "uaImpersonateMode": "0",
                "uaByOID": "",
                "clientProducts": null,
                "partnerUA": false
            },
            "user": {
                "isPractitioner": "false",
                "isiUserId": "amagana@guessw",
                "employeeId": "359089",
                "role": "EMPLOYEE",
                "roles": [
                    "EMPLOYEE"
                ],
                "rOids": ",77019870,,60001,,2000,,78051369,,2011000,,10013,,78051462,,900,,78051463,,60140,",
                "associateOId": "G3HX7Z0RX5XMCA9M"
            }
        }
    }
}